### ISSUE TITLE
confusing error

### ISSUE THREAD

**Issue by okjim3ML** [atuttle/mxunit-watch#9]
Hi Adam, I'm trying to set up mxunit-watch and I'm getting an error. When I run mxunit-watch from terminal I get "ERROR: Unable to load tests list. Did you enter the correct URL? (URL echoed back to me) Watching for file changes. Get coding!" If I make a file change I get the error message again so I know the watching part is working. If I run the test-list.cfm file directly in the browser I get a coldfusion error:
You have attempted to dereference a scalar variable of type class java.lang.Boolean as a structure with members. 
The error occurred in /Users/jokeefe/Sites/medicaremapping/v5/test-list.cfm: line 15
13 : 
14 :     for (t in tests){
15 :         tests[t] = tests[t].methods;
16 :     }
17 : </cfscript>

if I comment out the for loop in lines 14-16 the output of serializeJson(tests) is:
{"Empty" : false}
If I dump out files I get an array listing my the files in my test directory, that seems OK
If I dump out tests just before the for loop I get a linkedHashMap java object, but it has no data.
If I dump out suite after the suite.addAll() loop I can see my tests listed as methods in the testsuite instance. Any ideas what I'm doing wrong?

**Comment by seancoyne** [comment]
What version of CF are you on?

**Comment by okjim3ML** [comment]
cf 11

**Comment by seancoyne** [comment]
I had trouble w/ the default version of test-list.cfm on CF 9 (I see you're on CF11 but maybe there is a similar issue).  I created this version which is slightly different which works for me:

```coldfusion
<cfscript>
    testsDir = expandPath('/path/to/tests');
    componentPath = 'path.to.tests';

    suite = createObject('mxunit.framework.TestSuite');
    files = createObject('mxunit.runner.DirectoryTestSuite').getTests(directory=testsDir, componentPath=componentPath);

    for (i = 1; i <= arrayLen(files); i++){
        suite.addAll(files[i]);
    }

    testSuites = suite.suites();

    iterator = testSuites.entrySet().iterator();

    tests = {};
    while(iterator.hasNext()) {
        item = iterator.next();
        tests[item.getKey()] = item.getValue().methods;
    }
</cfscript>

<cfsetting showdebugoutput="false" />
<cfcontent reset="true" type="application/json; charset=UTF-8" /><cfoutput>#serializeJson(tests)#</cfoutput><cfabort/>
```

**Comment by okjim3ML** [comment]
That seems to have done the trick! Thanks Sean.

**Comment by atuttle** [comment]
If your version is more generally compatible, please submit it as a pull
request!
